[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "csst-ifs-gehong"
version = "0.0.1.1"
authors = [
  { name="Shuai Feng", email="sfeng@hebtu.edu.cn" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]