[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "gehong"
authors = [{name = "Shuai Feng", email = "sfeng@hebtu.edu.cn"}]
dynamic = ["version", "description"]
